apiVersion: v1
kind: Template
metadata:
  name: jenkins-slave-maven-appdev-build-template
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "jenkins-slave-maven-appdev"
  spec:
    output:
      to:
        kind: DockerImage
        name: docker-registry-default.apps.${CLUSTER}/${GUID}-jenkins/jenkins-slave-maven-appdev:v3.9
    postCommit: {}
    resources: {}
    source:
      type: "Dockerfile"
      dockerfile: "FROM docker.io/openshift/jenkins-slave-maven-centos7:v3.9\nUSER root\nRUN yum -y install skopeo apb && yum clean all\nUSER 1001"
    strategy:
      type: Docker
    triggers:
      - type: "ConfigChange"
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: jenkins-slave-maven-appdev
    name: jenkins-slave-maven-appdev
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-slave-maven-appdev:v3.9
      importPolicy: {}
      name: v3.9
      referencePolicy:
        type: ""
parameters:
- name: GUID
  displayName: GUID
  description: guid
  value: ddibarto
  required: true
- name: CLUSTER
  displayName: CLUSTER
  description: cluster
  value: na39.openshift.opentlc.com
  required: true
