apiVersion: v1
kind: Template
metadata:
  name: ${GUID}-mlbparks-pipeline-template
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "mlbparks-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "${REPO}"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: MLBParks/Jenkinsfile
        env:
          - name: "GUID"
            value: "${GUID}"
          - name: "CLUSTER"
            value: "${CLUSTER}"
parameters:
- name: REPO
  displayName: REPO
  description: repo
  value: https://github.com/ddibartolomei/advdev_homework_template
  required: true
- name: GUID
  displayName: GUID
  description: guid
  value: ddibarto
  required: true
- name: CLUSTER
  displayName: CLUSTER
  description: cluster
  value: na39.openshift.opentlc.com
  required: true
